//
//  PerformanceTests.swift
//  Phase 28b — wall-clock budgets for the user-facing slow paths
//  (openFile, find-in-files scan). Driven against the fixtures
//  generated by Scripts/gen_perf_samples.sh; tests skip themselves
//  if the fixtures aren't present so a fresh checkout still passes.
//
//  Why custom budgets instead of XCTest's `measure { }`: those metric
//  blocks regress against a per-machine baseline file, which makes
//  them noisy across developer hardware. We assert *absolute* budgets
//  ("openFile main-thread sync portion under 50 ms regardless of
//  file size") which model the user-perceived freeze instead.
//

import XCTest
@testable import Scribe

@MainActor
final class PerformanceTests: XCTestCase {

    // MARK: - Fixture resolution

    /// Returns the URL of the requested perf fixture, or `nil` if
    /// the file isn't generated yet. Lookup is relative to the
    /// repo's `Tests/Fixtures` directory; we walk up from the test
    /// bundle until we find it.
    private func fixtureURL(name: String) -> URL? {
        var dir = URL(fileURLWithPath: #filePath)
        for _ in 0..<6 {
            dir.deleteLastPathComponent()
            let candidate = dir
                .appendingPathComponent("Tests")
                .appendingPathComponent("Fixtures")
                .appendingPathComponent(name)
            if FileManager.default.fileExists(atPath: candidate.path) {
                return candidate
            }
        }
        return nil
    }

    // MARK: - openFile main-thread budget

    /// The synchronous portion of `Workspace.openFile(at:)` should
    /// be O(1) regardless of file size — read + decode is a detached
    /// Task. Anything over 50 ms means we accidentally re-introduced
    /// a sync I/O hop on the main thread.
    private func assertOpenFileSyncBudget(_ name: String) throws {
        guard let url = fixtureURL(name: name) else {
            throw XCTSkip("Fixture \(name) missing — run Scripts/gen_perf_samples.sh")
        }
        let prefs = EditorPreferences()
        let workspace = Workspace(prefs: prefs, openInitialUntitled: false)

        let t0 = DispatchTime.now()
        workspace.openFile(at: url)
        let elapsedNs = DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
        let elapsedMs = Double(elapsedNs) / 1_000_000

        XCTAssertLessThan(elapsedMs, 50,
                          "openFile sync portion \(elapsedMs) ms exceeded 50 ms budget for \(name)")
        // Confirm the placeholder document was registered immediately.
        XCTAssertEqual(workspace.documents.count, 1)
        XCTAssertTrue(workspace.documents[0].isLoading)
    }

    func test_openFile_1mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_1mb.txt")
    }

    func test_openFile_5mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_5mb.txt")
    }

    func test_openFile_20mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_20mb.txt")
    }

    // MARK: - Find-in-files scan budget

    /// Walking + scanning the perf fixtures with a non-matching
    /// pattern should complete in under 5 seconds for the 20 MB
    /// case — comfortably so, since the engine streams + skips
    /// binaries early. We pass an obscure literal so the engine
    /// touches every file but produces no matches.
    func test_findInFiles_20mb_scanCompletes() async throws {
        guard let url = fixtureURL(name: "perf_20mb.txt") else {
            throw XCTSkip("Fixture perf_20mb.txt missing — run Scripts/gen_perf_samples.sh")
        }
        let root = url.deletingLastPathComponent()
        let state = FindInFilesState()
        let engine = FindInFilesEngine()
        let opts = FindInFilesOptions(
            query: "ZZZ_no_such_token_in_lorem_ipsum_ZZZ",
            matchCase: true,
            wholeWord: false,
            regex: false,
            includeGlobs: ["perf_*.txt"],
            excludeGlobs: []
        )

        let t0 = DispatchTime.now()
        engine.search(options: opts, root: root, into: state)

        // Spin the main runloop in 50 ms slices until the engine
        // declares done or the budget is exceeded. Detached search
        // task posts back via MainActor.run, so we have to yield.
        var elapsedSeconds: Double = 0
        let budget: Double = 5.0
        while state.isSearching && elapsedSeconds < budget {
            try await Task.sleep(nanoseconds: 50_000_000)
            elapsedSeconds = Double(
                DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
            ) / 1_000_000_000
        }

        XCTAssertFalse(state.isSearching,
                       "find-in-files scan exceeded \(budget) s budget")
        XCTAssertEqual(state.totalMatches, 0,
                       "expected zero hits for the obscure-literal probe")
    }

    // MARK: - Baseline benchmarks (perf-A)
    //
    // These intentionally do *not* enforce a tight budget — they
    // exist to pin a current number into the test log so future
    // work can detect regressions. The wide ceilings are paranoia
    // stops: if any of these crosses them we'd want to investigate,
    // but the real numbers we expect are far below.
    //
    // See docs/perf_audit.md for the surrounding investigation.

    /// Pure ColorScanner.scan over the 5 MB perf fixture. Touches
    /// every byte once. Baselines the inline-color-swatch hot path
    /// (audit § L5 / I5).
    func test_colorScanner_scan_5mb_baseline() throws {
        guard let url = fixtureURL(name: "perf_5mb.txt") else {
            throw XCTSkip("Fixture perf_5mb.txt missing — run Scripts/gen_perf_samples.sh")
        }
        let text = try String(contentsOf: url, encoding: .utf8)

        let t0 = DispatchTime.now()
        let hits = ColorScanner.scan(text)
        let elapsedMs = Double(
            DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
        ) / 1_000_000

        // Lorem-ipsum fixture has zero color literals — the scan
        // path does the full O(n) sweep but emits nothing. That's
        // the worst case for pure overhead-per-byte.
        XCTAssertGreaterThanOrEqual(hits.count, 0)
        XCTAssertLessThan(elapsedMs, 5_000,
                          "BASELINE colorScanner.scan(5MB) = \(elapsedMs) ms")
    }

    /// MarkdownConverter.render over the 5 MB perf fixture
    /// reinterpreted as markdown. The fixture is plain prose so
    /// the output is mostly `<p>` blocks; the cost of the line-by
    /// -line BlockContext walk dominates. Baselines audit § L6.
    func test_markdownConverter_render_5mb_baseline() throws {
        guard let url = fixtureURL(name: "perf_5mb.txt") else {
            throw XCTSkip("Fixture perf_5mb.txt missing — run Scripts/gen_perf_samples.sh")
        }
        let text = try String(contentsOf: url, encoding: .utf8)

        let t0 = DispatchTime.now()
        _ = MarkdownConverter.render(text)
        let elapsedMs = Double(
            DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
        ) / 1_000_000

        XCTAssertLessThan(elapsedMs, 30_000,
                          "BASELINE markdownConverter.render(5MB) = \(elapsedMs) ms")
    }

    /// Synthetic git-blame porcelain (~7 700 lines / ~1 MB) parsed
    /// through the pure `GitClient.parseBlamePorcelain` entry point.
    /// Baselines audit § L4 / I5-I6 (the Inline Blame chain ends in
    /// this parser whenever cache misses force a refetch).
    func test_gitBlame_parsePorcelain_synthetic_baseline() throws {
        let lineCount = 7_700
        var raw = ""
        raw.reserveCapacity(lineCount * 130)
        for n in 1...lineCount {
            // Each block emits a fresh sha so the metadata cache
            // never short-circuits — worst case for the parser.
            let sha = String(format: "%040x", n)
            raw += "\(sha) \(n) \(n) 1\n"
            raw += "author Test Author \(n % 100)\n"
            raw += "author-mail <test\(n % 100)@example.com>\n"
            raw += "author-time \(1_700_000_000 + n)\n"
            raw += "author-tz +0000\n"
            raw += "committer Test Committer\n"
            raw += "committer-mail <c@example.com>\n"
            raw += "committer-time \(1_700_000_000 + n)\n"
            raw += "committer-tz +0000\n"
            raw += "summary baseline commit \(n)\n"
            raw += "filename perf.txt\n"
            raw += "\tsource line \(n)\n"
        }

        let t0 = DispatchTime.now()
        let lines = GitClient.parseBlamePorcelain(raw)
        let elapsedMs = Double(
            DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
        ) / 1_000_000

        XCTAssertEqual(lines.count, lineCount)
        XCTAssertLessThan(elapsedMs, 5_000,
                          "BASELINE parseBlamePorcelain(~\(lineCount) lines) = \(elapsedMs) ms")
    }

    /// End-to-end open: from `openFile(at:)` to `isLoading == false`.
    /// Covers the async decode hop + main-thread `applyLoadResult`,
    /// which is the path the user actually waits on. Baselines
    /// audit § L1 / L2 (the full load chain, not just the sync
    /// portion that the existing 50 ms tests cover).
    func test_workspace_openFile_endToEnd_5mb_baseline() async throws {
        guard let url = fixtureURL(name: "perf_5mb.txt") else {
            throw XCTSkip("Fixture perf_5mb.txt missing — run Scripts/gen_perf_samples.sh")
        }
        let prefs = EditorPreferences()
        let workspace = Workspace(prefs: prefs, openInitialUntitled: false)

        let t0 = DispatchTime.now()
        workspace.openFile(at: url)
        // Spin until the placeholder flips to loaded.
        var elapsedMs: Double = 0
        let budget: Double = 30_000
        while elapsedMs < budget {
            if let doc = workspace.documents.first, !doc.isLoading {
                break
            }
            try await Task.sleep(nanoseconds: 10_000_000)
            elapsedMs = Double(
                DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
            ) / 1_000_000
        }

        XCTAssertEqual(workspace.documents.count, 1)
        XCTAssertFalse(workspace.documents.first?.isLoading ?? true,
                       "BASELINE workspace.openFile end-to-end stuck after \(budget) ms")
        XCTAssertLessThan(elapsedMs, budget,
                          "BASELINE workspace.openFile(5MB) end-to-end = \(elapsedMs) ms")
    }
}
