//
//  PerformanceTests.swift
//  Phase 28b — wall-clock budgets for the user-facing slow paths
//  (openFile, find-in-files scan). Driven against the fixtures
//  generated by Scripts/gen_perf_samples.sh; tests skip themselves
//  if the fixtures aren't present so a fresh checkout still passes.
//
//  Why custom budgets instead of XCTest's `measure { }`: those metric
//  blocks regress against a per-machine baseline file, which makes
//  them noisy across developer hardware. We assert *absolute* budgets
//  ("openFile main-thread sync portion under 50 ms regardless of
//  file size") which model the user-perceived freeze instead.
//

import XCTest
@testable import Scribe

@MainActor
final class PerformanceTests: XCTestCase {

    // MARK: - Fixture resolution

    /// Returns the URL of the requested perf fixture, or `nil` if
    /// the file isn't generated yet. Lookup is relative to the
    /// repo's `Tests/Fixtures` directory; we walk up from the test
    /// bundle until we find it.
    private func fixtureURL(name: String) -> URL? {
        var dir = URL(fileURLWithPath: #filePath)
        for _ in 0..<6 {
            dir.deleteLastPathComponent()
            let candidate = dir
                .appendingPathComponent("Tests")
                .appendingPathComponent("Fixtures")
                .appendingPathComponent(name)
            if FileManager.default.fileExists(atPath: candidate.path) {
                return candidate
            }
        }
        return nil
    }

    // MARK: - openFile main-thread budget

    /// The synchronous portion of `Workspace.openFile(at:)` should
    /// be O(1) regardless of file size — read + decode is a detached
    /// Task. Anything over 50 ms means we accidentally re-introduced
    /// a sync I/O hop on the main thread.
    private func assertOpenFileSyncBudget(_ name: String) throws {
        guard let url = fixtureURL(name: name) else {
            throw XCTSkip("Fixture \(name) missing — run Scripts/gen_perf_samples.sh")
        }
        let prefs = EditorPreferences()
        let workspace = Workspace(prefs: prefs, openInitialUntitled: false)

        let t0 = DispatchTime.now()
        workspace.openFile(at: url)
        let elapsedNs = DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
        let elapsedMs = Double(elapsedNs) / 1_000_000

        XCTAssertLessThan(elapsedMs, 50,
                          "openFile sync portion \(elapsedMs) ms exceeded 50 ms budget for \(name)")
        // Confirm the placeholder document was registered immediately.
        XCTAssertEqual(workspace.documents.count, 1)
        XCTAssertTrue(workspace.documents[0].isLoading)
    }

    func test_openFile_1mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_1mb.txt")
    }

    func test_openFile_5mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_5mb.txt")
    }

    func test_openFile_20mb_under_50ms() throws {
        try assertOpenFileSyncBudget("perf_20mb.txt")
    }

    // MARK: - Find-in-files scan budget

    /// Walking + scanning the perf fixtures with a non-matching
    /// pattern should complete in under 5 seconds for the 20 MB
    /// case — comfortably so, since the engine streams + skips
    /// binaries early. We pass an obscure literal so the engine
    /// touches every file but produces no matches.
    func test_findInFiles_20mb_scanCompletes() async throws {
        guard let url = fixtureURL(name: "perf_20mb.txt") else {
            throw XCTSkip("Fixture perf_20mb.txt missing — run Scripts/gen_perf_samples.sh")
        }
        let root = url.deletingLastPathComponent()
        let state = FindInFilesState()
        let engine = FindInFilesEngine()
        let opts = FindInFilesOptions(
            query: "ZZZ_no_such_token_in_lorem_ipsum_ZZZ",
            matchCase: true,
            wholeWord: false,
            regex: false,
            includeGlobs: ["perf_*.txt"],
            excludeGlobs: []
        )

        let t0 = DispatchTime.now()
        engine.search(options: opts, root: root, into: state)

        // Spin the main runloop in 50 ms slices until the engine
        // declares done or the budget is exceeded. Detached search
        // task posts back via MainActor.run, so we have to yield.
        var elapsedSeconds: Double = 0
        let budget: Double = 5.0
        while state.isSearching && elapsedSeconds < budget {
            try await Task.sleep(nanoseconds: 50_000_000)
            elapsedSeconds = Double(
                DispatchTime.now().uptimeNanoseconds - t0.uptimeNanoseconds
            ) / 1_000_000_000
        }

        XCTAssertFalse(state.isSearching,
                       "find-in-files scan exceeded \(budget) s budget")
        XCTAssertEqual(state.totalMatches, 0,
                       "expected zero hits for the obscure-literal probe")
    }
}
